### ISSUE TITLE
DB migration not working

### ISSUE THREAD

**Issue by navneetccna** [nuwave/lighthouse-tutorial#2]
I am trying to install this example. But getting error with database migration. Also please add installation instructions for the same.

Also when I run http://localhost:8000/graphql, I am getting following error

{"errors":[{"message":"Syntax Error: Unexpected <EOF>","category":"graphql","locations":[{"line":1,"column":1}]}]}

**Comment by spawnia** [comment]
https://laravel.com/docs/database
